[build]
  functions = "/.netlify/functions"

  [functions]
  directory = "/.netlify/functions"
  node_bundler = "esbuild"


[[redirects]]
  from = "/api/*"
  to = ".netlify/functions/:splat" # Замените на порт, на котором работают функции Netlify в режиме разработки
  status = 200